version: '3.7'

services:

  server:
    image: hesham786/node-app:v1.0
    container_name: express
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=mongodb+srv://Hesham:hesham12345@clusterh.lcaaf.mongodb.net/?retryWrites=true&w=majority;
      - PORT=5000
    networks:
      - app-network

  client:
    image: hesham786/react-app:v1.0
    container_name: react
    volumes:
      - ./client/:/app
      - /app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
