version: '3.7'

services:

  server:
    image: fierce1/node-app1:v1.0
    container_name: express
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=mongodb+srv://Hesham:hesham12345@clusterh.lcaaf.mongodb.net/?retryWrites=true&w=majority;

  client:
    stdin_open: true
    image: fierce1/react-app1:v1.0
    container_name: react
    volumes:
      - ./client/:/app
      - /app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"



